// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiprKdeIbpC6-DkjNIqwyp_jmu8Cab_z0',
    appId: '1:595717296897:web:8851eb591ce69fec608100',
    messagingSenderId: '595717296897',
    projectId: 'referral-bd',
    authDomain: 'referral-bd.firebaseapp.com',
    storageBucket: 'referral-bd.appspot.com',
    measurementId: 'G-YQ6R2F62D5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFUt-fPjTqEOKCLkN9kcCA0VM6Z80cUz4',
    appId: '1:595717296897:android:61dcd706ba27da77608100',
    messagingSenderId: '595717296897',
    projectId: 'referral-bd',
    storageBucket: 'referral-bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbqsm4tUhROKYdd7kpxfEG5p6NXBwJtNc',
    appId: '1:595717296897:ios:ca40808f369831a0608100',
    messagingSenderId: '595717296897',
    projectId: 'referral-bd',
    storageBucket: 'referral-bd.appspot.com',
    iosBundleId: 'com.example.flutterReferralApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbqsm4tUhROKYdd7kpxfEG5p6NXBwJtNc',
    appId: '1:595717296897:ios:f4d6d61cc95e8867608100',
    messagingSenderId: '595717296897',
    projectId: 'referral-bd',
    storageBucket: 'referral-bd.appspot.com',
    iosBundleId: 'com.example.flutterReferralApp.RunnerTests',
  );
}
